#!/bin/bash


if [ "$1" == "-h" ] ; then
    echo "Usage: line_break_remover <in_file> (out will be prefix.nobreaks.fasta)>"
    exit 0
fi
if [ "$1" == "--help" ] ; then
    echo "Usage: line_break_remover <in_file> (out will be prefix.nobreaks.fasta)>"
    exit 0
fi

awk '/^>/{print s? s"\n"$0:$0;s="";next}{s=s sprintf("%s",$0)}END{if(s)print s}' $1 > $1.nobreaks.fasta
