#! /bin/bash

if [ "$1" == "-h" ] ; then
    echo "Usage: tfa_preparer <BORD00XXXX ID (will assume .fas and sequence headers within the .fas share the same ID> <gene_name (out will be gene_name.tfa)>"
    exit 0
fi
if [ "$1" == "--help" ] ; then
    echo "Usage: tfa_preparer <BORD00XXXX ID (will assume .fas and sequence headers within the .fas share the same ID> <gene_name (out will be gene_name.tfa)>"
    exit 0
fi

sed -i "s/$1/$2/g" $1.fas
line_break_remover $1.fas
mv $1.fas.nobreaks.fasta $2.tfa
